<script>
import BaseCheckbox from "./BaseCheckbox.vue";

/**
 * The form component for the SMS Consent checkbox
 * ```html
 * <form-sms-consent v-model="submit.smsConsent"/>
 * ```
 */
export default {
  extends: BaseCheckbox,
  props: {
    id: {
      default: "sms-consent"
    },

    stopCode: {
      type: String,
      default: "35254"
    },

    helpCode: {
      type: String,
      default: "35254"
    },

    termsLink: {
      type: String,
      default: "https://policies.edusites.net/terms"
    },

    privacyLink: {
      type: String,
      default: "https://policies.edusites.net/privacyus"
    }
  },

  computed: {
    labelContent() {
      return `I consent to receiving SMS/MMS messages generated by an autodialer from ${this.$root.schoolDisplayName} or its representatives at the mobile number I provided. Consent is not required to receive information. Message & data rates may apply. Send STOP to ${this.stopCode} to unsubscribe. Send HELP to ${this.helpCode} for help. Click here for <a target="_blank" href="${this.termsLink}">Terms & Conditions</a> and <a target="_blank" href="${this.privacyLink}">Privacy Policy</a>.`;
    }
  }
};
</script>
