<script>
import BaseCheckbox from "./BaseCheckbox.vue";

/**
 * The form component for the SMS Consent checkbox
 * ```html
 * <form-sms-consent v-model="submit.smsConsent"/>
 * ```
 */
export default {
  extends: BaseCheckbox,
  props: {
    id: {
      default: "sms-consent"
    }
  },

  computed: {
    labelContent() {
      return `<span class="label-title">SMS Consent</span>I consent to receiving SMS/MMS messages generated by an autodialer from ${this.$root.schoolDisplayName} or its representatives at the mobile number I provided. Consent is not required to receive information. Message & data rates may apply. Send STOP to 35254 to unsubscribe. Send HELP to 35254 for help. <a target="_blank" href="https://wiley.com/terms-privacy">Click here</a> for Terms & Conditions and Privacy Policy.`;
    }
  }
};
</script>
